export function TermsContentEn() {
  return (
    <>
      <h1 className="text-2xl font-bold">Terms of Service</h1>
      <p className="text-muted-foreground">Last updated: February 26, 2026</p>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">1. Service Overview</h2>
        <p>
          &ldquo;Real Weekly Report&rdquo; (hereinafter &ldquo;the
          Service&rdquo;) is a web service that analyzes your Google Calendar
          events and automatically generates AI-based weekly work reports.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">2. Terms of Use</h2>
        <ul className="list-disc space-y-1 pl-6">
          <li>A Google account is required to use this Service.</li>
          <li>
            You must agree to grant read-only access to your Google Calendar to
            this Service.
          </li>
          <li>
            This Service shall only be used for generating weekly work reports
            for business purposes.
          </li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">
          3. Service Provision and Changes
        </h2>
        <p>
          This Service is provided &ldquo;as-is.&rdquo; The content, features,
          and UI of the Service may be changed without prior notice.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">4. AI-Generated Content</h2>
        <ul className="list-disc space-y-1 pl-6">
          <li>
            Reports are automatically generated by AI (Google Gemini) and
            accuracy is not guaranteed.
          </li>
          <li>
            It is the user&apos;s responsibility to review and edit the generated
            reports.
          </li>
        </ul>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">5. Disclaimer</h2>
        <p>
          The service provider shall not be liable for any direct or indirect
          damages arising from the use of this Service. The user bears final
          responsibility for the content of AI-generated reports.
        </p>
      </section>

      <section className="space-y-2">
        <h2 className="text-lg font-semibold">6. Service Interruption</h2>
        <p>
          The service provider may temporarily suspend or terminate the Service
          without prior notice.
        </p>
      </section>
    </>
  );
}
